#! /bin/sh
# custom bspwm keybindings cheatsheet
notify-send -u normal -i \
"/usr/share/icons/Papirus-Dark/symbolic/devices/input-keyboard-symbolic.svg" \
"BSPWM keybindings:" \
"S + d           rofi\n\
S +            term\n\
S + Sh +       floating term\n\
S + 1-9	        go to ws\n\
S + Ctr + ,   go to ws\n\
S + Sh + 1-9	move window to ws\n\
S + f	        floating\n\
S + w	        monocle\n\
S + q	        close window\n\
S + Sh + q	quit wm\n\
S + l	        session menu\n\
S + Esc	        reload sxhkd\n\
S + Alt + e	reload bspwm\
"
