#! /bin/sh
# 12/09/23

# START APPS
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --set-zoom-fill --random ~/Pictures > /dev/null &
pkill picom & picom --experimental-backends -b &
# Variable Defines
color0=#3B4252
color4=#D8DEE9


#Fix Mouse curoor on startup 
xsetroot -cursor_name left_ptr

#Set Keyboard Layout
setxkbmap -layout us

#Monitor Config
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc monitor -d www dev meet work ent

#BSPWM Config
bspc config border_width        0
bspc config top_padding         30
bspc config right_padding       3
bspc config left_padding        3
bspc config bottom_padding      3
bspc config window_gap          3
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0
bspc config border-radius 30

bspc config focused_border_color "$color0"
bspc config normal_border_color  "$color0"
bspc config active_border_color  "$color0"
bspc config presel_feedback_color "$color4"
bspc config split_ratio          1
bspc config borderless_monocle   true  
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a *:my_float state=floating
